Demo of Docker Internal Networking Not Failing
OpenMined/Sonar pull request #21
Opened 2017-08-19 22:59 UTC by carrollgt91

Requires you to be on this branch: https://github.com/OpenMined/Sonar/pull/17 to `docker-compose build` and `docker-compose up`.

NOTE: THIS SHOULD PROBABLY NOT BE MERGED.

I put this up here just to make the folks who have been running into the Docker networking  issues mentioned here (https://github.com/OpenMined/Sonar/issues/13) were aware of a fix. See my comment on that issue for more information.

2017-08-20 09:47 UTC, anoff requested changes
Adding a blocking review..just in case

2017-08-20 09:59 UTC, anoff commented on docker-compose.yml
> +      context: ../Sonar
lol nice hack 🤣

2017-09-02 17:30 UTC, iamtrask commented
@anoff @carrollgt91 should I go ahead and close this PR?

2017-09-02 17:46 UTC, carrollgt91 commented
Yeah, it's likely very out of date at this point anyways 👍

> On Sep 2, 2017, at 12:30 PM, iamtrask <notifications@github.com> wrote:
> 
> @anoff @carrollgt91 should I go ahead and close this PR?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-09-02 17:46 UTC, closed without merging